name: easy_localization_loader
description: Easy Localization Loader custom assets loaders for easy_localization (Json, CSV, http, Xml, API ...)
# author: AISSAT abdelwahab <mr.aissat@gmail.com>
homepage: https://github.com/aissat/easy_localization_loader
issue_tracker: https://github.com/aissat/easy_localization_loader/issues

version: 1.0.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  http: ^0.13.1
  csv: ^5.0.0
  yaml: ^3.1.0
  xml: ^6.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter

